source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               src/,\
               bin/,\
               build.properties,\
               .project,\
               .classpath,\
               lib/awaitility-4.3.0.jar,\
               lib/hamcrest-3.0.jar
src.includes = bin/,\
               .settings/,\
